bo-archival/force-app/main/default/objects/Archival_Process__c/Archival_Process__c.object-meta.xml
<CustomObject>
    <description>Custom object to store record of Archival Process run</description>
    <label>Archival Process</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Process Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <description>Number of Records Archived</description>
    <inlineHelpText>Number of Records Archived</inlineHelpText>
    <label>Archived Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Archived_Till__c.field-meta.xml
<CustomField>
    <fullName>Archived_Till__c</fullName>
    <label>Archived Till</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Records</label>
    <type>Checkbox</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <label>Deleted Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Number of Records Failed</description>
    <inlineHelpText>Number of Records Failed</inlineHelpText>
    <label>Error Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <label>Selected Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Updated__c.field-meta.xml
<CustomField>
    <fullName>Updated__c</fullName>
    <label>Updated Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/CaseNumber__c.field-meta.xml
<CustomField>
    <fullName>CaseNumber__c</fullName>
    <label>Case Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <label>ClosedDate</label>
    <type>DateTime</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/ContactMobile__c.field-meta.xml
<CustomField>
    <fullName>ContactMobile__c</fullName>
    <label>Contact Mobile</label>
    <type>Phone</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/CreatedById__c.field-meta.xml
<CustomField>
    <fullName>CreatedById__c</fullName>
    <label>CreatedById</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <label>External_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/IsEscalated__c.field-meta.xml
<CustomField>
    <fullName>IsEscalated__c</fullName>
    <label>IsEscalated</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>ParentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/SuppliedEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppliedEmail__c</fullName>
    <label>Supplied Email</label>
    <type>Email</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/SuppliedName__c.field-meta.xml
<CustomField>
    <fullName>SuppliedName__c</fullName>
    <label>Supplied Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Case__b/fields/SuppliedPhone__c.field-meta.xml
<CustomField>
    <fullName>SuppliedPhone__c</fullName>
    <label>Supplied Phone</label>
    <type>Phone</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/Lead__b.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <pluralLabel>Leads</pluralLabel>
</CustomObject>

bo-archival/force-app/main/default/objects/Lead__b/fields/AnnualRevenue__c.field-meta.xml
<CustomField>
    <fullName>AnnualRevenue__c</fullName>
    <label>Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/ConvertedAccountId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAccountId__c</fullName>
    <label>Converted Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/ConvertedContactId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedContactId__c</fullName>
    <label>Converted Contact Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/ConvertedDate__c.field-meta.xml
<CustomField>
    <fullName>ConvertedDate__c</fullName>
    <label>Converted Date</label>
    <type>DateTime</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/CreatedById__c.field-meta.xml
<CustomField>
    <fullName>CreatedById__c</fullName>
    <label>Created By Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/GeocodeAccuracy__c.field-meta.xml
<CustomField>
    <fullName>GeocodeAccuracy__c</fullName>
    <label>Geocode Accuracy</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/HasOptedOutOfEmail__c.field-meta.xml
<CustomField>
    <fullName>HasOptedOutOfEmail__c</fullName>
    <label>Email Opt Out</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>Lead Id</description>
    <label>Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <label>Is Converted</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>Owner Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/PhotoURL__c.field-meta.xml
<CustomField>
    <fullName>PhotoURL__c</fullName>
    <label>Photo URL</label>
    <type>Url</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Lead__b/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/classes/ArchivalUtility.cls
public class ArchivalUtility implements Database.Batchable<sObject>, Database.Stateful {
    //To Store log entries
    private List<string> Log {get; set;}
    private List<string> ErrorLog {get; set;}
    private list<string> ErrorIds {get; set;}    
    //To store Process entry record
    private Archival_Process__c objProcess {get; set;}
    //To count number of iterations and errors
    private integer iterationCount {get; set;}
    private integer errorRecCount {get; set;}
    //Constructor to pass process Id
    public ArchivalUtility(id archivalProcessId)
    {
        List<Archival_Process__c> lstProcess = [ SELECT Id, Job_Id__c, Source_Object__c, Target_Object__c, Archived_Till__c, Delete_Records__c, Status__c, Batch_Size__c, Start_Time__c, End_Time__c, Selected__c, Archived__c, Deleted__c, Updated__c, Log__c, Has_Error__c FROM Archival_Process__c WHERE Id = :archivalProcessId AND Status__c = 'Queued'];
        if(lstProcess.size() == 1 )
        {
            objProcess = lstProcess.get(0);
            objProcess.Selected__c = 0;
            objProcess.Archived__c = 0;
            objProcess.Error__c = 0;
            objProcess.Deleted__c = 0;
            objProcess.Updated__c = 0;
            this.Log = new List<string>();
            this.ErrorLog = new List<string>();
            iterationCount = 0;
            errorRecCount = 0;
    	}
        else
        {
            objProcess = null;
            throw new ProcessException('No queued process not found with specified id: ' + archivalProcessId);
        }
    }
    //Start method to select records to be processed
    public Database.QueryLocator start(Database.BatchableContext bc) {
        objProcess.Job_Id__c = bc.getJobId();
        try
        {
            startProcessEntry();
			addToLog('Process Started', false);
            string strQuery = '';
            switch on objProcess.Source_Object__c.toUpperCase()
            {
                when 'CASE'
                {
                    strQuery = getCaseQuery();
                }
                when 'LEAD'
                {
                    strQuery = getLeadQuery();
                }
                when else
                {
					addToLog('No query defined for source object: ' + objProcess.Source_Object__c, true);
                }
            }
            
            Date tillDate = objProcess.Archived_Till__c.addDays(1);//required to pass parameter to query, adding one day and using < to avoid date time convesion issue
            return Database.getQueryLocator(strQuery);
        }
        catch(Exception ex)
        {
			addToLog(ex.getMessage(), true);
            System.debug('start: ' + ex.getMessage());
            throw ex;
        }
    }
    //Execute iteration to process batch of records
    public void execute(Database.BatchableContext bc, List<sObject> source) {
        string jobId = bc.getJobId();
        ++iterationCount;
        boolean hasError = false;
		addToLog('Itr ' + iterationCount + ': Start: ' + source.size(), false);
        List<sObject> lstTarget = new List<sObject>();
        try
        {
			objProcess.Selected__c = objProcess.Selected__c + source.size();
            
            for(sObject objSource : source)
            {
                if ( objSource instanceof Case)
                {
	                lstTarget.add(mapCase((Case) objSource));
                    ((Case) objSource).Archived__c = true;
                }
                else if ( objSource instanceof Lead )
                {
					lstTarget.add(mapLead((Lead) objSource));
                    ((Lead) objSource).Archived__c = true;
                }
                else
                    return;
            }
            
            //Insert in BO
            hasError = insertTarget(lstTarget, source, hasError);
            
            //Update to set flag as archived
            updateSource(source, hasError);
            
            //Delete if user chose to delete
            if(objProcess.Delete_Records__c)
	            deleteSource(source, hasError);
        }
        catch(Exception ex)
        {
            addToLog('Itr ' + iterationCount + ': Exception: ' + ex.getMessage(), true);
            System.debug('execute: ' + ex.getMessage());
        }
        finally
        {
            if(hasError)
                addToLog('Itr ' + iterationCount + ': Success', false);
            else
	            addToLog('Itr ' + iterationCount + ': Complete', false);
            
            //updated Archive Process records
			objProcess.Log__c = string.join(Log, '\n');
			objProcess.Error_Log__c = string.join(ErrorLog, '\n');            
			update objProcess;
        }
    }
    //Finish method to complete the process
    public void finish(Database.BatchableContext bc) {
        addToLog('Finishing Job.', false);
        finishProcessEntry();
    }
    //Method to insert in BO
    private boolean insertTarget(List<sObject> target, List<sObject> source, boolean hasError)
    {
        List<Database.SaveResult> lstResult = Database.insertImmediate(target);
        List<string> errors = getErrors(lstResult, source);
        
        if(errors.size() == 0)
        {
            hasError = false;
            objProcess.Archived__c = objProcess.Archived__c + target.size();
            addToLog('Insert done.', false);
        }
        else
        {
            hasError = true;
            ErrorLog.add('Itr (' + iterationCount +'): Insert errors:');
            ErrorLog.addAll(errors);
            objProcess.Archived__c = objProcess.Archived__c + target.size() - errorRecCount;
            objProcess.Error__c = objProcess.Error__c + errorRecCount;
            addToLog('Inserts except errors: ' + (target.size() - errorRecCount), true);
        }
        return hasError;
    }
    private void updateSource(List<sObject> source, boolean hasError)
    {
        List<Database.SaveResult> lstResult;
        integer recTried = source.size();
        if(hasError)
        {
            List<sObject> selected = new List<sObject>();
            for(sObject objSource : source)
            {
                if (! ErrorIds.contains(objSource.get('Id').toString()))
                {
                    selected.add(objSource);
                }
            }
            recTried = selected.size();
            lstResult = Database.updateImmediate(selected, System.AccessLevel.SYSTEM_MODE);
        }
        else
        {
            lstResult = Database.updateImmediate(source, System.AccessLevel.SYSTEM_MODE);
        }
        if(lstResult != null)
        {      
            List<string> errors = getErrors(lstResult, source);
            if(errors.size() == 0)
            {
                objProcess.Updated__c = objProcess.Updated__c + recTried;
                addToLog('Update done: ' + recTried, false);
            }
            else
            {
                ErrorLog.add('Itr (' + iterationCount +'): Update errors:');
                ErrorLog.addAll(errors);
                objProcess.Updated__c = objProcess.Updated__c + recTried - errorRecCount;
                objProcess.Error__c = objProcess.Error__c + errorRecCount;                    
                addToLog('Updates except errors: ' + (recTried - errors.size()), true);
            }
        }
    }
    
    private void deleteSource(List<sObject> source, boolean hasError)
    {
        List<Database.DeleteResult> lstResult;
        integer recTried = source.size();
        if(hasError)
        {
            List<sObject> selected = new List<sObject>();
            for(sObject objSource : source)
            {
                if (! ErrorIds.contains(objSource.get('Id').toString()))
                {
                    selected.add(objSource);
                }
            }
            recTried = selected.size();
            lstResult = Database.deleteImmediate(selected, System.AccessLevel.SYSTEM_MODE);
        }
        else
        {
        	lstResult = Database.deleteImmediate(source, System.AccessLevel.SYSTEM_MODE);
        } 
        
        List<string> errors = getErrors(lstResult, source);
        
        if(errors.size() == 0)
        {
            	objProcess.Deleted__c = objProcess.Deleted__c + recTried;
            	addToLog('Delete done: ' + recTried , false);
        }
        else
        {
            ErrorLog.add('Itr (' + iterationCount +'): errors in Delete:');
            ErrorLog.addAll(errors);
            objProcess.Deleted__c = objProcess.Deleted__c + recTried - errorRecCount;
            objProcess.Error__c = objProcess.Error__c + errorRecCount;                    
            addToLog('Deletes except errors: ' + (recTried - errors.size()) , true);
        }
    }
    
    //Method to append Log entry
    private void addToLog(string message, boolean hasError)
    {
        Log.add(DateTime.now() + ' : ' + message);
		if( hasError && ! objProcess.Has_Error__c )
        	objProcess.Has_Error__c = hasError;
    }
    //Method to get error records from Save result
    private List<string> getErrors(List<Database.SaveResult> results, List<sObject> source)
    {
        List<string> lstErrors = new List<string>();
        integer i = 0;
        errorRecCount =0;
        ErrorIds = new List<String>();
        sObject objSource;
        for(Database.SaveResult result : results)
        {
            if(!result.isSuccess())
            {
                errorRecCount++;
                objSource = source.get(i);
                ErrorIds.add(objSource.get('id').toString());
                
             	for(Database.Error error : result.getErrors())
                {
					lstErrors.add(objSource.get('id') + ': ' + error.getStatusCode() + ': ' + error.getMessage());
                }
            }
            i++;
        }
        return lstErrors;
    }
    //Method to get error records from Delete Result
    private List<string> getErrors(List<Database.DeleteResult> results, List<sObject> source)
    {
        List<string> lstErrors = new List<string>();
        integer i = 0;
        errorRecCount = 0;
        sObject objSource;      
        for(Database.DeleteResult result : results)
        {
            if(! result.isSuccess())
            {
                errorRecCount++;
                objSource = source.get(i);
             	for(Database.Error error : result.getErrors())
                {
					lstErrors.add(objSource.get('id') + ': ' + error.getStatusCode() + ': ' + error.getMessage());
                }
            }
            i++;
        }
        return lstErrors;
    }
    //Method to return SOQL for Case object
    private static string getCaseQuery()
    {
        return 'SELECT Id, CaseNumber, AccountId, Origin, Reason, RecordType.Name, SourceId, ContactEmail, ContactMobile, ContactId, CreatedById, ClosedDate, CreatedDate, Description, IsEscalated, External_ID__c, Comments, Status, Subject, Type, SuppliedEmail, SuppliedPhone, SuppliedName, ParentId, Priority FROM Case WHERE Archived__c = false AND CreatedDate < :tillDate';
    }
    //Method to return SOQL for Lead object
    private static string getLeadQuery()
    {
        return 'SELECT Id, LastName, FirstName, Salutation, Title, Company, Street, City, State, PostalCode, Country, Latitude, Longitude, GeocodeAccuracy, Phone, MobilePhone, Fax, Email, Website, PhotoURL, Description, LeadSource, Status, Industry, Rating, AnnualRevenue, NumberOfEmployees, OwnerId, HasOptedOutOfEmail, IsConverted, ConvertedDate, ConvertedAccountId, ConvertedContactId, ConvertedOpportunityId, CreatedDate, CreatedById, DoNotCall, IndividualId, External_Id__c FROM Lead WHERE Archived__c = false AND CreatedDate < :tillDate';
    }
    //Method to cast Case object to Case big object
    private static Case__b mapCase(Case objCase)
    {
        Case__b objCaseB = new Case__b();
        objCaseB.RecordId__c = objCase.Id;
        objCaseB.AccountId__c = objCase.AccountId;
        objCaseB.CaseNumber__c = objCase.CaseNumber;
        objCaseB.ClosedDate__c = objCase.ClosedDate;
        objCaseB.Comments__c = objCase.Comments;
        objCaseB.ContactEmail__c = objCase.ContactEmail;
        objCaseB.ContactId__c = objCase.ContactId;
        objCaseB.ContactMobile__c = objCase.ContactMobile;
        objCaseB.CreatedById__c = objCase.CreatedById;
        objCaseB.CreatedDate__c = objCase.CreatedDate;
        objCaseB.Description__c = objCase.Description;
        objCaseB.External_ID__c = objCase.External_ID__c;
        if( objCase.IsEscalated == true)
        	objCaseB.IsEscalated__c = 1;
        else
            objCaseB.IsEscalated__c = 0;
        objCaseB.Origin__c = objCase.Origin;
        objCaseB.ParentId__c = objCase.ParentId;
        objCaseB.Priority__c = objCase.Priority;
        objCaseB.Reason__c = objCase.Reason;
        objCaseB.RecordType__c = objCase.RecordTypeId;
        objCaseB.Source__c = objCase.SourceId;
        objCaseB.Status__c = objCase.Status;
        objCaseB.Subject__c = objCase.Subject;
        objCaseB.SuppliedEmail__c = objCase.SuppliedEmail;
        objCaseB.SuppliedName__c = objCase.SuppliedName;
        objCaseB.SuppliedPhone__c = objCase.SuppliedPhone;
    	return objCaseB;
    }
    //Method to cast Lead object to Lead big object
    private static Lead__b mapLead(Lead objLead)
    {
        Lead__b objLeadB = new Lead__b();
        objLeadB.Id__c = objLead.Id;
        objLeadB.LastName__c = objLead.LastName;
        objLeadB.FirstName__c = objLead.FirstName;
        objLeadB.Salutation__c = objLead.Salutation;
        objLeadB.Title__c = objLead.Title;
        objLeadB.Company__c = objLead.Company;
        objLeadB.Street__c = objLead.Street;
 		objLeadB.City__c = objLead.City;
        objLeadB.State__c = objLead.State;
        objLeadB.PostalCode__c = objLead.PostalCode;
        objLeadB.Country__c = objLead.Country;
        objLeadB.Latitude__c = objLead.Latitude;
        objLeadB.Longitude__c = objLead.Longitude;
        objLeadB.GeocodeAccuracy__c = objLead.GeocodeAccuracy;
        objLeadB.Phone__c = objLead.Phone;
        objLeadB.MobilePhone__c = objLead.MobilePhone;
        objLeadB.Fax__c = objLead.Fax;
        objLeadB.Email__c = objLead.Email;
        objLeadB.Website__c = objLead.Website;
        objLeadB.PhotoURL__c = objLead.PhotoURL;
        objLeadB.Description__c = objLead.Description;
        objLeadB.LeadSource__c = objLead.LeadSource;
        objLeadB.Status__c = objLead.Status;
        objLeadB.Industry__c = objLead.Industry;
        objLeadB.Rating__c = objLead.Rating;
        objLeadB.AnnualRevenue__c = objLead.AnnualRevenue;
        objLeadB.NumberOfEmployees__c = objLead.NumberOfEmployees;
        objLeadB.OwnerId__c = objLead.OwnerId;
        if( objLead.HasOptedOutOfEmail == true )
        	objLeadB.HasOptedOutOfEmail__c = 1;
        else
            objLeadB.HasOptedOutOfEmail__c = 0;
        if( objLead.IsConverted == true )
        	objLeadB.IsConverted__c = 1;
        else
        	objLeadB.IsConverted__c = 0;
        
        objLeadB.ConvertedDate__c = objLead.ConvertedDate;
        objLeadB.ConvertedAccountId__c = objLead.ConvertedAccountId;
        objLeadB.ConvertedContactId__c = objLead.ConvertedContactId;
        objLeadB.ConvertedOpportunityId__c = objLead.ConvertedOpportunityId;
        objLeadB.CreatedDate__c = objLead.CreatedDate;
        objLeadB.CreatedById__c = objLead.CreatedById;
		if (objLead.DoNotCall == true )
	        objLeadB.DoNotCall__c = 1;
        else
	        objLeadB.DoNotCall__c = 0;
        objLeadB.IndividualId__c = objLead.IndividualId;
        objLeadB.External_Id__c = objLead.External_Id__c;
    	return objLeadB;
    }
    //Method to set status and Start Time for Process entry
    private void startProcessEntry()
    {
        if(objProcess != null)
        {
            objProcess.Start_Time__c = DateTime.now();
            objProcess.Status__c = 'Started';
            update objProcess;
        }
        else
        {
            throw new ProcessException('startProcessEntry: Process entry not started.');
        }
    }
    //Method to set status, End Time and Log for Process entry    
    private void finishProcessEntry()
    {
        if(objProcess != null)
        {
            objProcess.Status__c = 'Finished';
            objProcess.End_Time__c = DateTime.now();
            objProcess.Log__c = string.join(Log, '\n');
			update objProcess;
        }
        else
        {
			throw new ProcessException('finishProcessEntry: Process entry not finished.');
        }
    }
    //Custom Exception
    private virtual class ProcessException extends Exception {}
}