bo-archival/force-app/main/default/objects/Archival_Process__c/Archival_Process__c.object-meta.xml
<CustomObject>
    <description>Custom object to store record of Archival Process run</description>
    <label>Archival Process</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Process Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archival Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <description>Number of Records Archived</description>
    <inlineHelpText>Number of Records Archived</inlineHelpText>
    <label>Archived Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Archived_Till__c.field-meta.xml
<CustomField>
    <fullName>Archived_Till__c</fullName>
    <label>Archived Till</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Delete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Records__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Records</label>
    <type>Checkbox</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <label>Deleted Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <label>Selected Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bo-archival/force-app/main/default/objects/Archival_Process__c/fields/Updated__c.field-meta.xml
<CustomField>
    <fullName>Updated__c</fullName>
    <label>Updated Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bo-archival/force-app/main/default/classes/ActionExecuteArchival.cls
public class ActionExecuteArchival {
    @InvocableMethod(label='Action Execute Archival' description='Action to execute archival batch process.' category='Big Objects')
    public static void executeArchival(List<Id> archivalProcessIds) {
        Id processId = archivalProcessIds.get(0);
        List<Archival_Process__c> lstProcess = [ SELECT Id, Job_Id__c, Source_Object__c, Target_Object__c, Archived_Till__c, Delete_Records__c, Status__c, Batch_Size__c, Start_Time__c, End_Time__c, Selected__c, Archived__c, Deleted__c, Updated__c, Log__c, Has_Error__c FROM Archival_Process__c WHERE Id = :processId AND Status__c = 'Queued'];

        if(lstProcess.size() == 1 )
        {
            Archival_Process__c objProcess = lstProcess.get(0);
        	ArchivalUtility objAu = new ArchivalUtility(objProcess.Id);
        	Database.executeBatch(objAu, Integer.valueOf(objProcess.Batch_Size__c));
        }
    }
}